import Head from "next/head";
import AppHeader from "./AppHeader";
import Modal from "./Modal";

export default function Layout({ children, title, className = "" }) {
  return (
    <>
      <Head>
        <title>{`Magic Demo | ${title}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppHeader />

      <Modal />

      <main className={`px-3 container py-12 space-y-12 ${className}`}>
        {children}
      </main>
    </>
  );
}
